/* eslint-disable no-unused-vars */

import moment from 'moment';

function getDay(day = 0) {
  return moment().add(day, 'days').format('YYYY.MM.DD');
}
function getTime(day = 0, second = 0) {
  return moment().add(day, 'days').add(second, 'seconds').format('YYYY.MM.DD HH:mm:ss');
}

export const initData = async (clientId, nextSeq) => {
  return {
    // 회원
    user: [
      {
        _id: await nextSeq('user'),
        email: 'p1@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: 'Greeny',
        phone: '01011111111',
        address: '서울 중구 퇴계로 324',
        type: 'seller',
        image: `/files/${clientId}/greeny.webp`,
        createdAt: getTime(-100, -60 * 60 * 3),
        updatedAt: getTime(-100, -60 * 60 * 3),
      },
      {
        _id: await nextSeq('user'),
        email: 'p2@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '행운목수',
        phone: '01022222222',
        address: '경상북도 구미시',
        type: 'seller',
        image: `/files/${clientId}/mincheol.webp`,
        createdAt: getTime(-50),
        updatedAt: getTime(-30, -60 * 60 * 3),
      },
      {
        _id: await nextSeq('user'),
        email: 'p3@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '금전수 장인',
        phone: '01033333333',
        address: '서울시 강동구 성내동',
        type: 'seller',
        image: `/files/${clientId}/jiwon.webp`,
        createdAt: getTime(-40, -60 * 30),
        updatedAt: getTime(-30, -60 * 20),
      },
      {
        _id: await nextSeq('user'),
        email: 'p4@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '식집사',
        phone: '01044444444',
        address: '서울시 강남구 삼성동 456',
        type: 'seller',
        image: `/files/${clientId}/plant1.webp`,
        createdAt: getTime(-40, -60 * 30),
        updatedAt: getTime(-30, -60 * 20),
      },
      {
        _id: await nextSeq('user'),
        email: 'p5@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '식물 고수',
        phone: '01055555555',
        address: '서울시 동대문구 창신동',
        type: 'seller',
        image: `/files/${clientId}/plant2.webp`,
        createdAt: getTime(-40, -60 * 30),
        updatedAt: getTime(-30, -60 * 20),
      },
      {
        _id: await nextSeq('user'),
        email: 'p6@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '새싹이',
        phone: '01066666666',
        address: '서울시 서초구 반포1동',
        type: 'seller',
        image: `/files/${clientId}/sprout.webp`,
        createdAt: getTime(-40, -60 * 30),
        updatedAt: getTime(-30, -60 * 20),
      },
      {
        _id: await nextSeq('user'),
        email: 'p7@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '스프링',
        phone: '01077777777',
        address: '서울시 성동구 왕십리로 121',
        type: 'seller',
        image: `/files/${clientId}/spring.webp`,
        createdAt: getTime(-40, -60 * 30),
        updatedAt: getTime(-30, -60 * 20),
      },
      {
        _id: await nextSeq('user'),
        email: 'p8@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '식물 농부',
        phone: '01088888888',
        address: '서울시 중구 서소문로 89-31',
        type: 'seller',
        image: `/files/${clientId}/peasant.webp`,
        createdAt: getTime(-40, -60 * 30),
        updatedAt: getTime(-30, -60 * 20),
      },
    ],
    // 상품(식물)
    product: [
      //산세베리아
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '산세베리아 사랑',
        scientificName: '산세베리아 (Sansevieria trifasciata)',
        introduction: '이름부터 우아한 산세베리아다.',
        humidity: '40 ~ 70%',
        grwhTp: '21~25℃',
        light: '낮은 광도(300~800 Lux)',
        adoptionDate: '2024-08-01',
        waterCycle: '5',
        content: '비료를 거의 요구하지않음, \n응애,깍지벌레,총채벌레,개각충 조심',
        mainImages: [
          {
            path: `/files/${clientId}/sanseberia.webp`,
            name: 'sanseberia.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 1,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      //목고 베고니아
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '고고 베고니아',
        scientificName: '목베고니아 (Begonia lucerna)',
        introduction: '안녕하세여 고고베고니아에요!',
        humidity: '40 ~ 70%',
        grwhTp: '21~25℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-08-02',
        waterCycle: '4',
        content: '목베고니아의 꽃말은 짝사랑',
        mainImages: [
          {
            path: `/files/${clientId}/begonia.webp`,
            name: 'begonia.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 1,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      //봉의꼬리
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '용의머리',
        scientificName: '봉의꼬리 (Pteris multifida)',
        introduction: '용이되고 싶은 꼬리입니다!',
        humidity: '70% 이상',
        grwhTp: '16~20℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-08-03',
        waterCycle: '4',
        content: '비료 필수! \n물 너무 많이 주지 않기!',
        mainImages: [
          {
            path: `/files/${clientId}/tail_of_dragon.webp`,
            name: 'tail_of_dragon.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 1,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      //행운목
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '행운의 행운목',
        scientificName: '행운목 (Dracaena fragrans)',
        introduction: '나에게도 행운을 가져다 주길!',
        humidity: '40 ~ 70%',
        grwhTp: '21~25℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-08-01',
        waterCycle: '4',
        content: '비료 필수 \n물 너무 많이 주지않기',
        mainImages: [
          {
            path: `/files/${clientId}/lucky_tree.webp`,
            name: 'lucky_tree.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 2,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      //가울테리아
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '가을의 가울테리아',
        scientificName: '가울테리아 (Gaultheria procumbens)',
        introduction: '가울테이라 입니다요!',
        humidity: '40 ~ 70%',
        grwhTp: '16~20℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-08-02',
        waterCycle: '3',
        content: '비료 필요 \n꽃색 분홍색',
        mainImages: [
          {
            path: `/files/${clientId}/gaul_teria.webp`,
            name: 'gaul_teria.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 2,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      //금전수
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '김전수',
        scientificName: '금전수 (Zamioculcas zamiifolia)',
        introduction: '돈전수입니다!!',
        humidity: '40 ~ 70%',
        grwhTp: '16~20℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-08-01',
        waterCycle: '5',
        content: '그늘진 곳에서 잘 견디지만, 실내 밝은 간접광이 더 좋다',
        mainImages: [
          {
            path: `/files/${clientId}/money_plant.webp`,
            name: 'money_plant.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 3,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      //새우란
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '새우깡',
        scientificName: '새우란 (Calanthe discolor spp.)',
        introduction: '새우깡 따라쟁이',
        humidity: '40 ~ 70%',
        grwhTp: '21~25℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-08-02',
        waterCycle: '3',
        content: '뿌리는 강장제로도 사용된다. \n대부분의 서양난이 착생란인데 비하여 동양란은 지생란이 많다. ',
        mainImages: [
          {
            path: `/files/${clientId}/shrimp_flower.webp`,
            name: 'shrimp_flower.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 3,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      //자란
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '내가 자란이라니',
        scientificName: '자란 (Bletilla striata)',
        introduction: '식물계의 장원영',
        humidity: '40 ~ 70%',
        grwhTp: '16~20℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-08-01',
        waterCycle: '3',
        content: '물 너무 많이 주지 말기',
        mainImages: [
          {
            path: `/files/${clientId}/jaran.webp`,
            name: 'jaran.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 4,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      //아이비
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '유혹의 소나타',
        scientificName: '아이비 (Hedera helix)',
        introduction: '진실한 사랑',
        humidity: '40 ~ 70%',
        grwhTp: '16~20℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-08-02',
        waterCycle: '5',
        content: '덩굴손이 있어서 다른 물체에 매달리는 특성이 있어 끈으로 연결시켜 유인하여 기를 수 있다. \n오존에 민감해 오존의 피해정도를 육안으로 확인할 수 있음',
        mainImages: [
          {
            path: `/files/${clientId}/ivy.webp`,
            name: 'ivy.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 4,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      // 몬스테라
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '몽스',
        scientificName: '몬스테라 (Monstera deliciosa)',
        introduction: '암어 몬스터',
        humidity: '70% 이상',
        grwhTp: '16~20℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-01-01',
        waterCycle: '5',
        content: '덩굴성 대형관엽식물로 6~8m 까지 자란다.\n잎은 어긋나고 성숙한 것은 지름 1m 정도',
        mainImages: [
          {
            path: `/files/${clientId}/monstera.webp`,
            name: 'monstera.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 5,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      // 구문초
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '뭉쵸',
        scientificName: '구문초 (Pelargonium rosium)',
        introduction: '모기퇴치 장인',
        humidity: '40 ~ 70%',
        grwhTp: '16~20℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-02-04',
        waterCycle: '9',
        content: '비료를 보통 요구함',
        mainImages: [
          {
            path: `/files/${clientId}/rose_geranium.webp`,
            name: 'rose_geranium.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 5,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      // 공작야자
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '공작이',
        scientificName: '공작공작야자 (Caryota mitis)야자',
        introduction: '식물인데 공작임',
        humidity: '70% 이상',
        grwhTp: '21~25℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2023-09-08',
        waterCycle: '9',
        content: '비료를 보통 요구함 \n배수잘됨',
        mainImages: [
          {
            path: `/files/${clientId}/caryota_mitis.webp`,
            name: 'caryota_mitis.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 6,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      // 글레코마
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '코코',
        scientificName: "글레코마 (Glecoma hederacea 'Variegata')",
        introduction: '코코로 핑퐁',
        humidity: '40 ~ 70%',
        grwhTp: '16~20℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-04-27',
        waterCycle: '9',
        content: '비료를 보통 요구함 \n진딧물 조심하기.',
        mainImages: [
          {
            path: `/files/${clientId}/glecoma.webp`,
            name: 'glecoma.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 6,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      // 덕구리난
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '오리 너구리',
        scientificName: '덕구리난 (Beaucarnea recurvata (Nolina tuberculata))',
        introduction: '플랜테리어 갑',
        humidity: '40% 미만',
        grwhTp: '21~25℃',
        light: '높은 광도(1,500~10,000 Lux)',
        adoptionDate: '2024-01-15',
        waterCycle: '9',
        content: '비대한 줄기에 수분을 저장하고 있어 과습한 경우에 줄기가 물러질 수 있다. \n실내가 고온건조하고 햇빛이 잘 드는 곳에서 자란다',
        mainImages: [
          {
            path: `/files/${clientId}/elephant_foot.webp`,
            name: 'elephant_foot.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 7,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      // 박쥐란
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '주렁이',
        scientificName: '박쥐란 (Platycerium bifurcatum)',
        introduction: '사슴뿔을 닮은 모습이 너무 매력적',
        humidity: '40 ~ 70%',
        grwhTp: '16~20℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-07-07',
        waterCycle: '5',
        content: '비료 필요함. \n잎 기부로부터 잎 끝까지의 형태는 V자형으로 상부에는 2~3회 우상으로 갈라져서 늘어진다',
        mainImages: [
          {
            path: `/files/${clientId}/staghorn_fern.webp`,
            name: 'staghorn_fern.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 7,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      // 동백
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '동백꽃필무렵',
        scientificName: '동백 (Camellia japonica)',
        introduction: '백설공주',
        humidity: '40 ~ 70%',
        grwhTp: '16~20℃',
        light: '높은 광도(1,500~10,000 Lux)',
        adoptionDate: '2024-08-06',
        waterCycle: '5',
        content: '꽃은 12~4월에 피어서 결실기는 가을이다. \n(“산다화“라 하며 약용으로 이용한다.)',
        mainImages: [
          {
            path: `/files/${clientId}/camellia.webp`,
            name: 'camellia.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 8,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      // 아이비
      {
        _id: await nextSeq('product'),
        price: 999,
        quantity: 999,
        name: '아잉',
        scientificName: '아이비 (Hedera helix)',
        introduction: '아이비 장인',
        humidity: '40 ~ 70%',
        grwhTp: '16~20℃',
        light: '중간 광도(800~1,500 Lux)',
        adoptionDate: '2024-05-05',
        waterCycle: '5',
        content: '잎이 난형으로 밝은 녹색이고 가장자리에 엉성한 톱니가 있다.',
        mainImages: [
          {
            path: `/files/${clientId}/hedera_helix.webp`,
            name: 'hedera_helix.webp',
          },
        ],
        show: true,
        shippingFees: 0,
        seller_id: 8,
        active: true,
        buyQuantity: 0,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
    ],
    // 주문
    order: [],
    // 후기
    reply: [],
    // 장바구니
    cart: [],
    // 즐겨찾기/북마크
    bookmark: [
      //식물 북마크
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'product',
        target_id: 8,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'product',
        target_id: 16,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'product',
        target_id: 7,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'product',
        target_id: 10,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'product',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'product',
        target_id: 3,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'product',
        target_id: 15,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'product',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'product',
        target_id: 9,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'product',
        target_id: 17,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'product',
        target_id: 16,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'product',
        target_id: 8,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'product',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 6,
        type: 'product',
        target_id: 10,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 6,
        type: 'product',
        target_id: 14,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 6,
        type: 'product',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 6,
        type: 'product',
        target_id: 3,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 7,
        type: 'product',
        target_id: 4,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 7,
        type: 'product',
        target_id: 17,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 8,
        type: 'product',
        target_id: 11,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 8,
        type: 'product',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      //게시글 북마크
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'post',
        target_id: 42,
        memo: '저희 가을 열매가 열렸길래 조심스럽게 자랑해봅니다...ㅎㅎㅎㅎ',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'post',
        target_id: 40,
        memo: '아직 식린이인데 어디서부터 어떻게 시작해야할지 모르겠어서요,,, \n식린이에게 식물 추천해주세요!',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'post',
        target_id: 38,
        memo: '몬스테라를 잎을 수경으로 키우고 있는데요! \n수경으로 키울때 주의할점 없는지 궁금합니다!!',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'post',
        target_id: 37,
        memo: '우리 자란이,,,매일 보지만 정말 너무 이뻐요! \n만약 사람으로 태어났으면 장원영급 아닐까요?',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'post',
        target_id: 46,
        memo: '1인 사무실을 운영중입니다! \n아무래도 사무실이 너무 심심하다보니 식물을 놓아봤는데요 어떤가요??',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'post',
        target_id: 45,
        memo: '예전부터 마당있는 집에서 식물을 키우는게 로망이거든여! \n이제 시골로 내려와 도전해볼까하는데 \n사진에 보이는 곳에 어떤식물을 키우는게 좋을까요?',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'post',
        target_id: 44,
        memo: '아직 꽃이 안펴서 기대중인데 새우란은 어떤 꽃색이 있나요??',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 6,
        type: 'post',
        target_id: 43,
        memo: '지금 아이비를 키우고 있어서요 화분으로 포인트를 주고싶은데.. \n혹시 추천해주실만한거 있나요?',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 7,
        type: 'post',
        target_id: 41,
        memo: '겉으로 보기에는 괜찮은데 자세히 보면 아이가 많이 시들었어요,,, \n꽃모양은 괜찮지만 혹시 전문가분 계실까요?ㅜㅜ',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 8,
        type: 'post',
        target_id: 40,
        memo: '아직 식린이인데 어디서부터 어떻게 시작해야할지 모르겠어서요,,, \n식린이에게 식물 추천해주세요!',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      //북마크 유저
      //1
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'user',
        target_id: 3,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'user',
        target_id: 5,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'user',
        target_id: 7,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'user',
        target_id: 8,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'user',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      //2
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'user',
        target_id: 4,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'user',
        target_id: 6,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'user',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      //3
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'user',
        target_id: 4,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'user',
        target_id: 5,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      //4
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'user',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'user',
        target_id: 3,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'user',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      //5
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'user',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'user',
        target_id: 6,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'user',
        target_id: 4,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      //6
      {
        _id: await nextSeq('bookmark'),
        user_id: 6,
        type: 'user',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 6,
        type: 'user',
        target_id: 8,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 6,
        type: 'user',
        target_id: 7,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 6,
        type: 'user',
        target_id: 3,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      //7
      {
        _id: await nextSeq('bookmark'),
        user_id: 7,
        type: 'user',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 7,
        type: 'user',
        target_id: 8,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      //8
      {
        _id: await nextSeq('bookmark'),
        user_id: 8,
        type: 'user',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 8,
        type: 'user',
        target_id: 3,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 8,
        type: 'user',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
    ],
    // QnA, 공지사항, 게시판
    post: [
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 일기 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 1,
        seller_id: 1,
        title: '물을 줬다.',
        content: '물을 줬다. \n 며칠동안 깜빡하고 있다가 물을 줬다. \n 베리아야 미안해~',
        extra: {
          plantState: '좋음',
          action: '물주기',
          actionDate: '2024-08-08',
        },
        image: [
          {
            path: `/files/${clientId}/sanseberia_day2.webp`,
            name: 'sanseberia_day2.webp',
          },
        ],
        views: 1,
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 8,
        seller_id: 4,
        title: '갑자기 지인을 통해 꽃을 키우게 되었다.',
        content: '갑자기 지인을 통해 꽃을 키우게 되었다. \n 자란이라고 하는데, 굉장히 화사한 꽃이다.',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-03',
        },
        image: [
          {
            path: `/files/${clientId}/jaran_day1.webp`,
            name: 'jaran_day1.webp',
          },
        ],
        views: 1,
        user: {
          _id: 4,
          name: '식집사',
          image: `/files/${clientId}/plant1.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 6,
        seller_id: 3,
        title: '세 번째로 키우는 금전수이다.',
        content: '세 번째로 키우는 금전수이다. \n 물을 잘못 줘서 떠나보낸 앞선 금전수들... \n 이번엔 잘 키워야지',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-02',
        },
        image: [
          {
            path: `/files/${clientId}/money_tree_day1.webp`,
            name: 'money_tree_day1.webp',
          },
        ],
        views: 1,
        user: {
          _id: 3,
          name: '금전수 장인',
          image: `/files/${clientId}/jiwon.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 2,
        seller_id: 1,
        title: '너무 예쁜 베고니아!',
        content: '너무 예쁜 베고니아! \n 내 눈엔 그 어떤 꽃보다도 예쁘다. \n 잘 자라렴~',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-18',
        },
        image: [
          {
            path: `/files/${clientId}/begonia_day1.webp`,
            name: 'begonia_day1.webp',
          },
        ],
        views: 1,
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 2,
        seller_id: 1,
        title: '오늘은 베고니아에게 물을 주었다.',
        content: '오늘은 베고니아에게 물을 주었다. \n 어제 줬었어야 했는데 하루 정도는 괜찮겠지...?',
        extra: {
          plantState: '좋음',
          action: '물주기',
          actionDate: '2024-08-19',
        },
        image: [
          {
            path: `/files/${clientId}/begonia_day2.webp`,
            name: 'begonia_day2.webp',
          },
        ],
        views: 1,
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 12,
        seller_id: 6,
        title: '공작아 잘 크자!',
        content: '공작이가 예상보다 잘 자라지 못하는 것 같아서\n영양제 하나 주고 있습니다.\n영양제 먹고 잘 컸으면 좋겠습니다.',
        extra: {
          plantState: '좋음',
          action: '영양',
          actionDate: '2024-08-14',
        },
        image: [
          {
            path: `/files/${clientId}/caryota_mitis_d1.webp`,
            name: 'caryota_mitis_d1.webp',
          },
        ],
        views: 10,
        user: {
          _id: 6,
          name: '새싹이',
          image: `/files/${clientId}/sprout.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 10,
        seller_id: 5,
        title: '몽스 물 주기',
        content: '울 몽스에게 물을 줍니다. 잘 자라줘서 고마워',
        extra: {
          plantState: '좋음',
          action: '물주기',
          actionDate: '2024-08-14',
        },
        image: [
          {
            path: `/files/${clientId}/monstera_d2.webp`,
            name: 'monstera_d2.webp',
          },
          {
            path: `/files/${clientId}/monstera_d3.webp`,
            name: 'monstera_d3.webp',
          },
        ],
        views: 10,
        user: {
          _id: 5,
          name: '식물 고수',
          image: `/files/${clientId}/plant2.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 16,
        seller_id: 8,
        title: '겨울의 동백꽃',
        content: '이 추운 겨울에 어떻게 그렇게 꽃을 피우니\n너의 강인한 모습 놀라워.',
        extra: {
          plantState: '개화',
          action: '관찰',
          actionDate: '2024-01-11',
        },
        image: [
          {
            path: `/files/${clientId}/camellia_d1.webp`,
            name: 'camellia_d1.webp',
          },
        ],
        views: 10,
        user: {
          _id: 8,
          name: '식물 농부',
          image: `/files/${clientId}/peasant.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 15,
        seller_id: 7,
        title: '따뜻한 햇살을 즐기는 주렁이',
        content: '햇볕과 주렁이의 모습이 너무 예쁘다\n사진으로 남길 수 밖에 없는 모습',
        extra: {
          plantState: '좋음',
          action: '햇빛',
          actionDate: '2024-08-09',
        },
        image: [
          {
            path: `/files/${clientId}/staghorn_fern_d4.webp`,
            name: 'staghorn_fern_d4.webp',
          },
        ],
        views: 10,
        user: {
          _id: 7,
          name: '스프링',
          image: `/files/${clientId}/spring.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 11,
        seller_id: 5,
        title: '힘내자 뭉쵸야',
        content: '모기를 쫓아줘!!!',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-26',
        },
        image: [
          {
            path: `/files/${clientId}/rose_geranium_d1.webp`,
            name: 'rose_geranium_d1.webp',
          },
        ],
        views: 10,
        user: {
          _id: 5,
          name: '식물 고수',
          image: `/files/${clientId}/plant2.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 2,
        seller_id: 1,
        title: '베고니아를 그저 바라봤다.',
        content: '베고니아를 그저 바라봤다. \n 보기만 해도 힐링되고 기분이 좋다.',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-20',
        },
        image: [
          {
            path: `/files/${clientId}/begonia_day3.webp`,
            name: 'begonia_day3.webp',
          },
        ],
        views: 1,
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 3,
        seller_id: 1,
        title: '봉의꼬리를 분양받았다.',
        content: '봉의꼬리를 분양받았다. \n 하지만 난 이 녀석의 이름을 용의 머리라고 지을 거다.',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-22',
        },
        image: [
          {
            path: `/files/${clientId}/tail_of_dragon_day1.webp`,
            name: 'tail_of_dragon_day1.webp',
          },
        ],
        views: 1,
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 3,
        seller_id: 1,
        title: '한국의 야생화 봉의 꼬리...',
        content: '한국의 야생화 봉의 꼬리... \n 잎과 줄기가 가늘어 키우기가 힘든 녀석 같다. \n 조금 시들어가는 것 같다.',
        extra: {
          plantState: '아픔',
          action: '관찰',
          actionDate: '2024-08-25',
        },
        image: [
          {
            path: `/files/${clientId}/tail_of_dragon_day2.webp`,
            name: 'tail_of_dragon_day2.webp',
          },
        ],
        views: 1,
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 3,
        seller_id: 1,
        title: '아무래도 시들어가는 것 같아서 영양제를 놔주었다.',
        content: '아무래도 시들어가는 것 같아서 영양제를 놔주었다. \n 아프지 말아~',
        extra: {
          plantState: '아픔',
          action: '영양',
          actionDate: '2024-08-27',
        },
        image: [
          {
            path: `/files/${clientId}/tail_of_dragon_day3.webp`,
            name: 'tail_of_dragon_day3.webp',
          },
        ],
        views: 1,
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 4,
        seller_id: 2,
        title: '행운을 가져다 주는 행운목...',
        content: '행운을 가져다 주는 행운목... \n 나에게도 행운을 가져다 주길',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-01',
        },
        image: [
          {
            path: `/files/${clientId}/lucky_tree_day1.webp`,
            name: 'lucky_tree_day1.webp',
          },
        ],
        views: 1,
        user: {
          _id: 2,
          name: '행운목수',
          image: `/files/${clientId}/mincheol.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 4,
        seller_id: 2,
        title: '직장에서 승진했다.',
        content: '직장에서 승진했다. \n 행운목 덕분에 행운이 들어온 것 같다.',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-08',
        },
        image: [
          {
            path: `/files/${clientId}/lucky_tree_day2.webp`,
            name: 'lucky_tree_day2.webp',
          },
        ],
        views: 1,
        user: {
          _id: 2,
          name: '행운목수',
          image: `/files/${clientId}/mincheol.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 13,
        seller_id: 6,
        title: '코코 이삿날!',
        content: '코코가 요즘 너무 잘 컸는데,\n그에비해 집은 너무 좁은 것 같아서\n이사를 시켜줬습니다.\n새 집에서도 잘 크자 코코야~',
        extra: {
          plantState: '좋음',
          action: '분갈이',
          actionDate: '2024-08-03',
        },
        image: [
          {
            path: `/files/${clientId}/glecoma_d1.webp`,
            name: 'glecoma_d1.webp',
          },
        ],
        views: 10,
        user: {
          _id: 6,
          name: '새싹이',
          image: `/files/${clientId}/sprout.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 14,
        seller_id: 7,
        title: '구리야 아프지마',
        content: '구리야 너 아퍼?\n왜 이렇게 힘이 없어진 것 같니..\n내가 더 잘 할게\n아프지마',
        extra: {
          plantState: '아픔',
          action: '영양',
          actionDate: '2024-08-24',
        },
        image: [
          {
            path: `/files/${clientId}/elephant_foot_d1.webp`,
            name: 'elephant_foot_d1.webp',
          },
        ],
        views: 10,
        user: {
          _id: 7,
          name: '스프링',
          image: `/files/${clientId}/spring.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 8,
        seller_id: 4,
        title: '자란이는 너무 예쁜 꽃이다.',
        content: '자란이는 너무 예쁜 꽃이다. \n 오늘은 자란이를 바라보며 힐링했다.',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-10',
        },
        image: [
          {
            path: `/files/${clientId}/jaran_day2.webp`,
            name: 'jaran_day2.webp',
          },
        ],
        views: 1,
        user: {
          _id: 4,
          name: '식집사',
          image: `/files/${clientId}/plant1.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 5,
        seller_id: 2,
        title: '한여름에 분양받은 가울테리아...',
        content: '한여름에 분양받은 가울테리아... \n 하지만 너의 이름은 가을의 가울테리아야!',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-16',
        },
        image: [
          {
            path: `/files/${clientId}/gaul_teria_day1.webp`,
            name: 'gaul_teria_day1.webp',
          },
        ],
        views: 1,
        user: {
          _id: 2,
          name: '행운목수',
          image: `/files/${clientId}/mincheol.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 1,
        seller_id: 1,
        title: '무럭무럭 크는 중...',
        content: '무럭무럭 크는 중... \n 잘 자라고 있는 것 같아 뿌듯하다.',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-15',
        },
        image: [
          {
            path: `/files/${clientId}/sanseberia_day3.webp`,
            name: 'sanseberia_day3.webp',
          },
        ],
        views: 1,
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 5,
        seller_id: 2,
        title: '너무 귀여운 가울테리아!',
        content: '너무 귀여운 가울테리아! 열매 맺힌 게 너무 앙증맞다.',
        extra: {
          plantState: '좋음',
          action: '햇빛',
          actionDate: '2024-08-18',
        },
        image: [
          {
            path: `/files/${clientId}/gaul_teria_day2.webp`,
            name: 'gaul_teria_day2.webp',
          },
        ],
        views: 1,
        user: {
          _id: 2,
          name: '행운목수',
          image: `/files/${clientId}/mincheol.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },

      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 6,
        seller_id: 3,
        title: '세 번째 키우는 식물이라 그런지',
        content: '세 번째 키우는 식물이라 그런지 이번에는 잘 자라고 있는 것 같아 기분이 좋다.',
        extra: {
          plantState: '좋음',
          action: '물주기',
          actionDate: '2024-08-09',
        },
        image: [
          {
            path: `/files/${clientId}/money_tree_day2.webp`,
            name: 'money_tree_day2.webp',
          },
        ],
        views: 1,
        user: {
          _id: 3,
          name: '금전수 장인',
          image: `/files/${clientId}/jiwon.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 7,
        seller_id: 3,
        title: '제주에서 자생하는 난초 식물 새우란!',
        content: '제주에서 자생하는 난초 식물 새우란! \n 키우기가 어렵다는데, 어쨌든 분양받아 왔다.',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-17',
        },
        image: [
          {
            path: `/files/${clientId}/shrimp_flower_day1.webp`,
            name: 'shrimp_flower_day1.webp',
          },
        ],
        views: 1,
        user: {
          _id: 3,
          name: '금전수 장인',
          image: `/files/${clientId}/jiwon.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 1,
        seller_id: 1,
        title: '산세베리아를 지인에게서 분양받아왔다.',
        content: '산세베리아를 지인에게서 분양받아왔다. \n 참 고풍스러운 식물이다.',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-01',
        },
        image: [
          {
            path: `/files/${clientId}/sanseberia_day1.webp`,
            name: 'sanseberia_day1.webp',
          },
        ],
        views: 1,
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 15,
        seller_id: 7,
        title: '울 주렁이 큰 집 가자~',
        content: '주렁이 분갈이 해줬다\n원래 집은 너무 작아졌지?\n이사헀는데 적응 잘해~',
        extra: {
          plantState: '좋음',
          action: '분갈이',
          actionDate: '2024-08-11',
        },
        image: [
          {
            path: `/files/${clientId}/staghorn_fern_d1.webp`,
            name: 'staghorn_fern_d1.webp',
          },
          {
            path: `/files/${clientId}/staghorn_fern_d2.webp`,
            name: 'staghorn_fern_d2.webp',
          },
          {
            path: `/files/${clientId}/staghorn_fern_d3.webp`,
            name: 'staghorn_fern_d3.webp',
          },
        ],
        views: 10,
        user: {
          _id: 7,
          name: '스프링',
          image: `/files/${clientId}/spring.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 17,
        seller_id: 8,
        title: '머리 숱 친 아잉이',
        content: '아잉이의 숱이 너무 많아 한 번 쳤다.\n깔끔하니 보기 좋네!!\n이쁘다 아잉아 ㅎㅎ',
        extra: {
          plantState: '좋음',
          action: '가지',
          actionDate: '2024-08-10',
        },
        image: [
          {
            path: `/files/${clientId}/hedera_helix_d1.webp`,
            name: 'hedera_helix_d1.webp',
          },
        ],
        views: 10,
        user: {
          _id: 8,
          name: '식물 농부',
          image: `/files/${clientId}/peasant.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 13,
        seller_id: 6,
        title: '감동... 코코 꽃 폈다...',
        content: '울 코코가 개화했습니다.\n내 새끼 처럼 공 들여서 키웠는데\n꽃까지 피니 너무 좋네요 ㅜㅜ\n잘 커줘서 고마워 코코야',
        extra: {
          plantState: '개화',
          action: '관찰',
          actionDate: '2024-08-14',
        },
        image: [
          {
            path: `/files/${clientId}/glecoma_d2.webp`,
            name: 'glecoma_d2.webp',
          },
          {
            path: `/files/${clientId}/glecoma_d3.webp`,
            name: 'glecoma_d3.webp',
          },
        ],
        views: 10,
        user: {
          _id: 6,
          name: '새싹이',
          image: `/files/${clientId}/sprout.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 17,
        seller_id: 8,
        title: '후회된다.',
        content: '아잉아 미안해\n더 잘 돌봐줬어야했는데...\n관심을 많이 주지 못해서 너가 시들어버렸네..\n마음이 아프다...',
        extra: {
          plantState: '죽음',
          action: '관찰',
          actionDate: '2024-08-26',
        },
        image: [
          {
            path: `/files/${clientId}/hedera_helix_d2.webp`,
            name: 'hedera_helix_d2.webp',
          },
        ],
        views: 10,
        user: {
          _id: 8,
          name: '식물 농부',
          image: `/files/${clientId}/peasant.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 10,
        seller_id: 5,
        title: '울 몽스',
        content: '방 한 켠에 있는 울 몽이\n 넘 귀엽다',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-01',
        },
        image: [
          {
            path: `/files/${clientId}/montera_d1.webp`,
            name: 'montera_d1.webp',
          },
        ],
        views: 10,
        user: {
          _id: 5,
          name: '식물 고수',
          image: `/files/${clientId}/plant2.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 9,
        seller_id: 4,
        title: '플라스틱 분이 건조가 빠른 것 같아',
        content: '플라스틱 분이 건조가 빠른 것 같아 아예 물통에 담아 분갈이를 해줬다.',
        extra: {
          plantState: '아픔',
          action: '분갈이',
          actionDate: '2024-08-25',
        },
        image: [
          {
            path: `/files/${clientId}/ivy_day2.webp`,
            name: 'ivy_day2.webp',
          },
        ],
        views: 1,
        user: {
          _id: 4,
          name: '식집사',
          image: `/files/${clientId}/plant1.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 7,
        seller_id: 3,
        title: '노란색 꽃잎의 새우란',
        content: '노란색 꽃잎의 새우란 \n 드디어 개화했다. \n 꽃이 참 고급져 보이는 꽃이다. 오늘은 햇빛을 좀 쬐어줬다.',
        extra: {
          plantState: '개화',
          action: '햇빛',
          actionDate: '2024-08-18',
        },
        image: [
          {
            path: `/files/${clientId}/shrimp_flower_day2.webp`,
            name: 'shrimp_flower_day2.webp',
          },
        ],
        views: 1,
        user: {
          _id: 3,
          name: '금전수 장인',
          image: `/files/${clientId}/jiwon.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 9,
        seller_id: 4,
        title: '아이비를 분양받아왔다.',
        content: '아이비를 분양받아왔다. \n 분양받아온 기념으로 물을 줬다.',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-17',
        },
        image: [
          {
            path: `/files/${clientId}/ivy_day1.webp`,
            name: 'ivy_day1.webp',
          },
        ],
        views: 1,
        user: {
          _id: 4,
          name: '식집사',
          image: `/files/${clientId}/plant1.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 게시글 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '식물 추천받아요!',
        content: '지금 식물을 3종이나 키우고 있는데 더 키우고싶은 마음에 추천받아요!',
        repliesCount: 2,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 2,
              name: '행운목수',
              image: `/files/${clientId}/mincheol.webp`,
            },
            content: '가울테리어 추천드려요!! 제가 키우고 있는데 제 피드에 놀러오세요!',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 3,
              name: '금전수 장인',
              image: `/files/${clientId}/jiwon.webp`,
            },
            content: '지금 현재도 엄청 많이 키우시는거 같은데요?',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 8,
        extra: {
          category: 'free',
        },
        image: [
          {
            path: `/files/${clientId}/post_free_1.webp`,
            name: 'post_free_1.webp',
          },
        ],
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '행운목 질문입니다.',
        content: 'ㅜㅜㅜ끝에 잎 갈라진거 보이시나요?? \n분명 영양도 잘해주고 물도 잘줬는데,,, 왜이러는지 아시는분...',
        repliesCount: 1,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 5,
              name: '식물 고수',
              image: `/files/${clientId}/plant2.webp`,
            },
            content: '영양제는 어떤걸 주셨나요??',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 40,
        extra: {
          category: 'qna',
        },
        image: [
          {
            path: `/files/${clientId}/post_qna_2.webp`,
            name: 'post_qna_2.webp',
          },
        ],
        user: {
          _id: 2,
          name: '행운목수',
          image: `/files/${clientId}/mincheol.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '감성샷 한스푼.',
        content: '날씨도 흐릿하고 간만에 카메라 꺼내서 찍어봤는데 \n우리 김전수 인생샷 찍어줬네요 ㅋㅋ',
        repliesCount: 1,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 1,
              name: 'Greeny',
              image: `/files/${clientId}/greeny.webp`,
            },
            content: '오오오!!! 직업이 사진작가 이신가요? 완전 이뻐요!',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 3,
        extra: {
          category: 'planterior',
        },
        image: [
          {
            path: `/files/${clientId}/post_planterior_3.webp`,
            name: 'post_planterior_3.webp',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: `/files/${clientId}/jiwon.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '식물ver. 장원영',
        content: '우리 자란이,,,매일 보지만 정말 너무 이뻐요! \n만약 사람으로 태어났으면 장원영급 아닐까요?',
        repliesCount: 1,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 6,
              name: '새싹이',
              image: `/files/${clientId}/sprout.webp`,
            },
            content: 'ㅋㅋㅋ;;;장원영은 건들지 말죠..',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 20,
        extra: {
          category: 'free',
        },
        image: [
          {
            path: `/files/${clientId}/post_free_4.webp`,
            name: 'post_free_4.webp',
          },
          {
            path: `/files/${clientId}/post_free_4-1.webp`,
            name: 'post_free_4-1.webp',
          },
        ],
        user: {
          _id: 4,
          name: '식집사',
          image: `/files/${clientId}/plant1.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '몬스테라 질문이요!',
        content: '몬스테라를 잎을 수경으로 키우고 있는데요! \n수경으로 키울때 주의할점 없는지 궁금합니다!!',
        repliesCount: 2,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 8,
              name: '식물 농부',
              image: `/files/${clientId}/peasant.webp`,
            },
            content: '우와! 신엽 너무 크고 이쁜거 같아요!!!',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 5,
              name: '식물 고수',
              image: `/files/${clientId}/plant2.webp`,
            },
            content: '네!! 감사합니당~ 저두 더 잘자라길 바라고있어요!',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 30,
        extra: {
          category: 'qna',
        },
        image: [
          {
            path: `/files/${clientId}/post_qna_5.webp`,
            name: 'post_qna_5.webp',
          },
        ],
        user: {
          _id: 5,
          name: '식물 고수',
          image: `/files/${clientId}/plant2.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '덩굴 식물 국룰',
        content: '역시 덩굴 식물은 이런 위커 바구니랑 제일 잘어울리는거 같아요!',
        repliesCount: 0,
        replies: [],
        views: 0,
        extra: {
          category: 'planterior',
        },
        image: [
          {
            path: `/files/${clientId}/post_planterior_6.webp`,
            name: 'post_planterior_6.webp',
          },
          {
            path: `/files/${clientId}/post_planterior_6-1.webp`,
            name: 'post_planterior_6-1.webp',
          },
        ],
        user: {
          _id: 6,
          name: '새싹이',
          image: `/files/${clientId}/sprout.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '초보자도 쉽게 키울수있는 식물!',
        content: '아직 식린이인데 어디서부터 어떻게 시작해야할지 모르겠어서요,,, \n식린이에게 식물 추천해주세요!',
        repliesCount: 1,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 5,
              name: '식물 고수',
              image: `/files/${clientId}/plant2.webp`,
            },
            content: '몬스테라 추천합니다!! 초보자도 어렵지않게 키울수있어요!',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 5,
        extra: {
          category: 'planterior',
        },
        image: [],
        user: {
          _id: 7,
          name: '스프링',
          image: `/files/${clientId}/spring.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '목베고니아 질문!! 급해요ㅜㅜ',
        content: '겉으로 보기에는 괜찮은데 자세히 보면 아이가 많이 시들었어요,,, \n꽃모양은 괜찮지만 혹시 전문가분 계실까요?ㅜㅜ',
        repliesCount: 1,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 2,
              name: '행운목수',
              image: `/files/${clientId}/mincheol.webp`,
            },
            content: '정확한 상태는 모르겠지만 제가 봤을때는 문제가 없어보여요!',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 9,
        extra: {
          category: 'qna',
        },
        image: [
          {
            path: `/files/${clientId}/post_qna_10.webp`,
            name: 'post_qna_10.webp',
          },
          {
            path: `/files/${clientId}/post_qna_10-1.webp`,
            name: 'post_qna_10-1.webp',
          },
          {
            path: `/files/${clientId}/post_qna_10-2.webp`,
            name: 'post_qna_10-2.webp',
          },
        ],
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '우리 가을이!',
        content: '저희 가을 열매가 열렸길래 조심스럽게 자랑해봅니다...ㅎㅎㅎㅎ',
        repliesCount: 2,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 4,
              name: '식집사',
              image: `/files/${clientId}/plant1.webp`,
            },
            content: '조심스러게 말고 완전 자랑해주세요!!!ㅋㅋㅋ \n너무 이쁜걸요?',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 3,
              name: '금전수 장인',
              image: `/files/${clientId}/jiwon.webp`,
            },
            content: '다음에는 전체샷 보여주세요!! 궁금합니다!',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 10,
        extra: {
          category: 'free',
        },
        image: [
          {
            path: `/files/${clientId}/post_free_11.webp`,
            name: 'post_free_11.webp',
          },
        ],
        user: {
          _id: 2,
          name: '행운목수',
          image: `/files/${clientId}/mincheol.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '플랜테리어 조언 구합니다!',
        content: '지금 아이비를 키우고 있어서요 화분으로 포인트를 주고싶은데.. \n혹시 추천해주실만한거 있나요?',
        repliesCount: 0,
        replies: [],
        views: 3,
        extra: {
          category: 'qna',
        },
        image: [],
        user: {
          _id: 4,
          name: '식집사',
          image: `/files/${clientId}/plant1.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '새우란 키워보신분?',
        content: '아직 꽃이 안펴서 기대중인데 새우란은 어떤 꽃색이 있나요??',
        repliesCount: 2,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 1,
              name: 'Greeny',
              image: `/files/${clientId}/greeny.webp`,
            },
            content: '보라색,분홍색??정도 봤던거 같아요!',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 7,
              name: '스프링',
              image: `/files/${clientId}/spring.webp`,
            },
            content: '노랑색이 제일 유명한걸로 알고있습니다~',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 27,
        extra: {
          category: 'qna',
        },
        image: [
          {
            path: `/files/${clientId}/poat_qna_12.webp`,
            name: 'poat_qna_12.webp',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: `/files/${clientId}/jiwon.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '마당있는 집입니다!',
        content: '예전부터 마당있는 집에서 식물을 키우는게 로망이거든여! \n이제 시골로 내려와 도전해볼까하는데 \n사진에 보이는 곳에 어떤식물을 키우는게 좋을까요?',
        repliesCount: 2,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 1,
              name: 'Greey',
              image: `/files/${clientId}/plant2.webp`,
            },
            content: '일단...보이는 잡초부터 뽑고 다시 물어보셔야겠는걸요,,?',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 3,
              name: '금전수 장인',
              image: `/files/${clientId}/jiwon.webp`,
            },
            content: '흠...도전해보신다면 금식나무 어떠신가요??초보자도 키우기 쉬워서요!',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 13,
        extra: {
          category: 'qna',
        },
        image: [
          {
            path: `/files/${clientId}/post_qna_8.webp`,
            name: 'post_qna_8.webp',
          },
        ],
        user: {
          _id: 8,
          name: '식물 농부',
          image: `/files/${clientId}/peasant.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '사무실 인테리어 어떤가요?',
        content: '1인 사무실을 운영중입니다! \n아무래도 사무실이 너무 심심하다보니 식물을 놓아봤는데요 어떤가요??',
        repliesCount: 3,
        replies: [
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 7,
              name: '스프링',
              image: `/files/${clientId}/spring.webp`,
            },
            content: '오오?사진 완전 이쁘게 찍으셨다~',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 8,
              name: '식물 농부',
              image: `/files/${clientId}/peasant.webp`,
            },
            content: '역시 식물만큼 빈자리 채워주는건 없죠!',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
          {
            _id: await nextSeq('reply'),
            user: {
              _id: 8,
              name: '식물 농부',
              image: `/files/${clientId}/peasant.webp`,
            },
            content: '식물이 답답해 할 수 있으니 햇빛 많이 보게해주세요^^',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 23,
        extra: {
          category: 'planterior',
        },
        image: [
          {
            path: `/files/${clientId}/post_planterior_9.webp`,
            name: 'post_planterior_9.webp',
          },
        ],
        user: {
          _id: 1,
          name: 'Greeny',
          image: `/files/${clientId}/greeny.webp`,
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
    ],
    // 코드
    code: [
      {
        _id: 'activePost',
        title: '활성 게시판',
        codes: [
          {
            sort: 2,
            code: 'AP01',
            value: '문의 게시판',
            active: false, // 활성 여부
          },
          {
            sort: 1,
            code: 'AP02',
            value: '정보 공유', // 게시판 이름
            active: true,
          },
          {
            sort: 3,
            code: 'AP03',
            value: '음악 신청',
            active: true,
          },
        ],
      },
    ],
    // 설정
    config: [
      {
        _id: 'shippingFees',
        title: '배송비',
        value: 3500,
      },
      {
        _id: 'freeShippingFees',
        title: '배송비 무료 금액',
        value: 50000,
      },
    ],
  };
};
