/* eslint-disable no-unused-vars */

import moment from 'moment';

function getDay(day = 0) {
  return moment().add(day, 'days').format('YYYY.MM.DD');
}
function getTime(day = 0, second = 0) {
  return moment().add(day, 'days').add(second, 'seconds').format('YYYY.MM.DD HH:mm:ss');
}

export const initData = async (clientId, nextSeq) => {
  return {
    // 회원
    user: [
      {
        _id: await nextSeq('user'),
        email: 'p1@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '쑥쑤루쑥',
        phone: '01012345678',
        address: '경기도 남양주시 진접읍',
        type: 'seller',
        image: `/files/${clientId}/leeBadcuk.jpg`,
        createdAt: getTime(-100, -60 * 60 * 3),
        updatedAt: getTime(-100, -60 * 60 * 3),
      },
      {
        _id: await nextSeq('user'),
        email: 'p2@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '선장',
        phone: '01022334455',
        address: '경상북도 구미시',
        type: 'seller',
        image: `/files/${clientId}/mincheol.jpg`,
        createdAt: getTime(-50),
        updatedAt: getTime(-30, -60 * 60 * 3),
      },
      {
        _id: await nextSeq('user'),
        email: 'p3@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '금전수 장인',
        phone: '01033337777',
        address: '서울시 강동구 성내동',
        type: 'seller',
        image: `/files/${clientId}/jiwon.jpeg`,
        createdAt: getTime(-40, -60 * 30),
        updatedAt: getTime(-30, -60 * 20),
      },
      {
        _id: await nextSeq('user'),
        email: 'p4@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '식집사',
        phone: '01022223333',
        address: '서울시 강남구 삼성동 456',
        type: 'seller',
        image: `/files/${clientId}/plant1.jpg`,
        createdAt: getTime(-40, -60 * 30),
        updatedAt: getTime(-30, -60 * 20),
      },
      {
        _id: await nextSeq('user'),
        email: 'p5@plant.com',
        password: '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '식물고수',
        phone: '01022224444',
        address: '서울시 강남구 삼성동 456',
        type: 'seller',
        image: `/files/${clientId}/plant2.jpg`,
        createdAt: getTime(-40, -60 * 30),
        updatedAt: getTime(-30, -60 * 20),
      },
    ],
    // 상품(식물)
    product: [
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        scientificName: '칼리디움',
        name: '베리베리',
        grwhTp: '16~20℃',
        waterCycle: 3,
        humidity: '40 ~ 70%',
        adoptionDate: '2024-08-07',
        light: '중간 광도(800~1,500 Lux)',
        content: '안녕하세요 \n실험 해볼게요\n도전',
        price: 999,
        shippingFees: 999,
        show: true,
        active: true,
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/caladium.jpg`,
            name: 'caladium.jpg',
          },
        ],
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        scientificName: '군자란',
        name: '란장이',
        grwhTp: '16~20℃',
        humidity: '40 ~ 70%',
        waterCycle: 15,
        adoptionDate: '2024-07-28',
        light: '중간 광도(800~1,500 Lux)',
        content: '잘생김 \n실험 해볼게요\n도전',
        price: 999,
        shippingFees: 999,
        show: true,
        active: true,
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/clivia.jpg`,
            name: 'clivia.jpg',
          },
        ],
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        scientificName: '알로카시아 쿠쿨라타',
        name: '카시아',
        grwhTp: '16~20℃',
        humidity: '40 ~ 70%',
        waterCycle: 15,
        adoptionDate: '2024-06-08',
        light: '중간 광도(800~1,500 Lux)',
        content: '안녕하세요 \n실험 해볼게요\n도전',
        price: 999,
        shippingFees: 999,
        show: true,
        active: true,
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/alocasia.webp`,
            name: 'alocasia.webp',
          },
        ],
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        scientificName: '금전수',
        name: '돈들어와라',
        grwhTp: '16~20℃',
        humidity: '40 ~ 70%',
        waterCycle: 9,
        adoptionDate: '2024-05-17',
        light: '중간 광도(800~1,500 Lux)',
        content: '첫째 아이 \n복용하면 위험 \n비료 필수',
        price: 999,
        shippingFees: 999,
        show: true,
        active: true,
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/zamiya.jpg`,
            name: 'zamiya.jpg',
          },
        ],
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      {
        _id: await nextSeq('product'),
        seller_id: 3,
        scientificName: '동백',
        name: '동백이',
        grwhTp: '16~20℃',
        humidity: '40 ~ 70%',
        waterCycle: 9,
        adoptionDate: '2024-01-14',
        light: '중간 광도(800~1,500 Lux)',
        content: '안녕하세요 \n실험 해볼게요\n도전',
        price: 999,
        shippingFees: 999,
        show: true,
        active: true,
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/camellia.webp`,
            name: 'camellia.webp',
          },
        ],
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      {
        _id: await nextSeq('product'),
        seller_id: 3,
        scientificName: '디지고데카',
        name: '데카링',
        grwhTp: '16~20℃',
        humidity: '40 ~ 70%',
        waterCycle: 3,
        adoptionDate: '2024-04-15',
        light: '중간 광도(800~1,500 Lux)',
        content: '역시 경험이 없으면 키우기 힘들것 같다 \n추천해줄때 주의할것.',
        price: 999,
        shippingFees: 999,
        show: true,
        active: true,
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/dizygotheca.webp`,
            name: 'dizygotheca.webp',
          },
        ],
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      {
        _id: await nextSeq('product'),
        seller_id: 3,
        scientificName: '만년청',
        name: '청이',
        grwhTp: '	21~25℃',
        humidity: '40 ~ 70%',
        waterCycle: 3,
        adoptionDate: '2024-08-15',
        light: '중간 광도(800~1,500 Lux)',
        content: '발화계절	9~10월 가을 \n꽃색	노랑색 \n열매색	빨강색',
        price: 999,
        shippingFees: 999,
        show: true,
        active: true,
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/rohdea.jpg`,
            name: 'rohdea.jpg',
          },
        ],
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        scientificName: '개운죽',
        name: '개굴개굴',
        grwhTp: '16~20℃',
        humidity: '40 ~ 70%',
        waterCycle: 3,
        adoptionDate: '2024-03-13',
        light: '중간 광도(800~1,500 Lux)',
        content: '화분은 1-2주에 한번씩 충분히 관수 \n비료를 거의 요구하지않음',
        price: 999,
        shippingFees: 999,
        show: true,
        active: true,
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/dracaena.webp`,
            name: 'dracaena.webp',
          },
        ],
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      {
        _id: await nextSeq('product'),
        seller_id: 4,
        scientificName: '산세베리아',
        name: '산세',
        grwhTp: '	21~25℃',
        humidity: '40 ~ 70%',
        waterCycle: 9,
        adoptionDate: '2024-06-15',
        light: '낮은 광도(300~800 Lux)',
        content: '병해충	\n응애,깍지벌레,총채벌레,개각충실',
        price: 999,
        shippingFees: 999,
        show: true,
        active: true,
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/sansevieria.jpg`,
            name: 'sansevieria.jpg',
          },
        ],
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
      {
        _id: await nextSeq('product'),
        seller_id: 5,
        scientificName: '싱고니움',
        name: '싱글이',
        grwhTp: '21~25℃',
        humidity: '40 ~ 70%',
        waterCycle: 15,
        adoptionDate: '2024-08-16',
        light: '중간 광도(800~1,500 Lux)',
        content: '잎색이 다양한데,, \n우리 싱글이도 신기한 색이 나왔으면 좋겠다..',
        price: 999,
        shippingFees: 999,
        show: true,
        active: true,
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/syngonium.jpg`,
            name: 'syngonium.jpg',
          },
        ],
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
      },
    ],
    // 주문
    order: [],
    // 후기
    reply: [],
    // 장바구니
    cart: [],
    // 즐겨찾기/북마크
    bookmark: [
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'product',
        target_id: 9,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'product',
        target_id: 10,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'product',
        target_id: 9,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'product',
        target_id: 10,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'product',
        target_id: 9,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'product',
        target_id: 10,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'product',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'product',
        target_id: 4,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'user',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'user',
        target_id: 3,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'user',
        target_id: 4,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        type: 'user',
        target_id: 5,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'user',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'user',
        target_id: 3,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'user',
        target_id: 4,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 2,
        type: 'user',
        target_id: 5,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'user',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'user',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'user',
        target_id: 4,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 3,
        type: 'user',
        target_id: 5,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'user',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'user',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'user',
        target_id: 3,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 4,
        type: 'user',
        target_id: 5,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'user',
        target_id: 1,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'user',
        target_id: 2,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'user',
        target_id: 3,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 5,
        type: 'user',
        target_id: 4,
        createdAt: getTime(-3, -60 * 60 * 2),
      },
    ],
    // QnA, 공지사항, 게시판
    post: [
      //일기
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 1,
        seller_id: 1,
        views: 10,
        title: '베리베리~',
        content: '베리베리가 있어서 그런지 집들어오는게 기대된다! \n 좋아~',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-08-16',
        },
        image: [
          {
            path: `/files/${clientId}/caladium.jpg`,
            name: 'PlantImg1.png',
          },
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
        ],

        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 1,
        seller_id: 1,
        views: 22,
        title: '오늘의 베리!',
        content: '우리 베리베리가 잘자라고 있다 \n 좋아~',
        extra: {
          plantState: '좋음',
          action: '물주기',
          actionDate: '2024-08-10',
        },
        image: [
          {
            path: `/files/${clientId}/caladium.jpg`,
            name: 'PlantImg1.png',
          },
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
        ],

        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 1,
        seller_id: 1,
        views: 23,
        title: '오늘의 할일!',
        content: '우리 베리베리가 몸이 안좋은거같다... \n그래서 영양을 듬뿍해줬다!! \n건강하게 자라렴!',
        extra: {
          plantState: '아픔',
          action: '영양',
          actionDate: '2024-08-27',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
        ],

        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 1,
        seller_id: 1,
        views: 10,
        title: '관찰하기~',
        content: '우리 베리베리 \n아주 이쁘게자라렴!',
        extra: {
          plantState: '좋음',
          action: '관찰',
          actionDate: '2024-09-10',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
        ],
        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },

        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 4,
        seller_id: 1,
        views: 20,
        title: '관찰일지!',
        content: '우리 전수씨!! 새싹이 자라구 있구나!?!',
        extra: {
          plantState: '새싹',
          action: '관찰',
          actionDate: '2024-08-20',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
        ],
        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },

        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 4,
        seller_id: 1,
        views: 40,
        title: '전수야 잘가,,,',
        content: '우리 전수가 내가 관리를 잘못해서 가버렸다,,, \n전수야 너랑 행복했어...',
        extra: {
          plantState: '죽음',
          action: '관찰',
          actionDate: '2024-08-26',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg4.png`,
            name: 'PlantImg4.png',
          },
        ],
        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 8,
        seller_id: 1,
        views: 10,
        title: '우리 개굴이!',
        content: '개굴아!! 드뎌 꽃이 폈구나!? \n역시 너무 이뻐~',
        extra: {
          plantState: '개화',
          action: '햇빛',
          actionDate: '2024-08-26',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
        ],
        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 8,
        seller_id: 1,
        views: 30,
        title: '우리 개굴이~',
        content: '개굴아!! 오늘도 이쁘구나~',
        extra: {
          plantState: '좋음',
          action: '물주기',
          actionDate: '2024-08-21',
        },

        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
        ],
        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 2,
        seller_id: 2,
        views: 4,
        title: '우리 란장이 이쁘죠?',
        content: '란장아 무럭무럭 자라나라~',
        extra: {
          plantState: '좋음',
          action: '물주기',
          actionDate: '2024-08-11',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
        ],
        user: {
          _id: 2,
          name: '선장',
          image: '/files/03-Greeny/mincheol.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 2,
        seller_id: 2,
        views: 7,
        title: '란장이가 아파요 ㅜㅜ',
        content: '란장아 영양제 잘 먹고 건강해져야해 ㅜㅜ',
        extra: {
          plantState: '아픔',
          action: '영양',
          actionDate: '2024-08-20',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
        ],
        user: {
          _id: 2,
          name: '선장',
          image: '/files/03-Greeny/mincheol.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 3,
        seller_id: 2,
        views: 50,
        title: '카시아가 개화했다',
        content: '너무 예쁘다 ㅜㅜㅜ \n 정성스레 키운 보람이 있네',
        extra: {
          plantState: '개화',
          action: '햇빛',
          actionDate: '2024-08-12',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
          {
            path: `/files/${clientId}/PlantImg4.png`,
            name: 'PlantImg4.png',
          },
        ],
        user: {
          _id: 2,
          name: '선장',
          image: '/files/03-Greeny/mincheol.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 3,
        seller_id: 2,
        views: 50,
        title: '카시아가 죽었다...',
        content: '마음이 아프다. 더 잘 돌봐줬어야 하는데..',
        extra: {
          plantState: '죽음',
          action: '관찰',
          actionDate: '2024-08-19',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
        ],
        user: {
          _id: 2,
          name: '선장',
          image: '/files/03-Greeny/mincheol.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 2,
        seller_id: 2,
        views: 20,
        title: '란장이 새싹이 피었다.',
        content: '너무 작고 귀엽다 ㅎㅎ \n쑥쑥 잘 크면 좋겠네 \n열심히 키워야지~~',
        extra: {
          plantState: '새싹',
          action: '관찰',
          actionDate: '2024-10-05',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
        ],
        user: {
          _id: 2,
          name: '선장',
          image: '/files/03-Greeny/mincheol.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 3,
        seller_id: 2,
        views: 5,
        title: '카시아가 걱정된다..',
        content: '요즘 많이 시들시들해서 조금 걱정이다..',
        extra: {
          plantState: '아픔',
          action: '영양제',
          actionDate: '2024-08-04',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
        ],
        user: {
          _id: 2,
          name: '선장',
          image: '/files/03-Greeny/mincheol.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 5,
        seller_id: 3,
        views: 10,
        title: '자라나라 새싹새싹',
        content: '새싹아 돋아나라!! \n 이번 주 안에 새싹을 피웠으면...',
        extra: {
          plantState: '좋음',
          action: '물주기',
          actionDate: '2024-08-10',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: '/files/03-Greeny/jiwon.jpeg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 5,
        seller_id: 3,
        views: 50,
        title: '드디어 개화!!',
        content: '관심 준 만큼 예쁘게 잘 자라나서 아주 기분이 좋다. \n 완전히 개화될 때면 팔아야지',
        extra: {
          plantState: '개화',
          action: '관찰',
          actionDate: '2024-08-19',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: '/files/03-Greeny/jiwon.jpeg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 6,
        seller_id: 3,
        views: 2,
        title: '왜 아픈 건지 모르겠음',
        content: '똑같은 다른 디지고데카 잘 자라는데 \n 이 아이만 비실대서 \n 혹이 토양이 안 맞는가 싶어서 \n 분갈이를 했다.',
        extra: {
          plantState: '아픔',
          action: '분갈이',
          actionDate: '2024-08-27',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: '/files/03-Greeny/jiwon.jpeg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 6,
        seller_id: 3,
        views: 50,
        title: '분갈이 후 영양제 스팀팩 주사',
        content: '반드시 살리리라!\n 넌 할 수 있어! \n 살아나라 데카링!',
        extra: {
          plantState: '아픔',
          action: '영양',
          actionDate: '2024-08-28',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg4.png`,
            name: 'PlantImg4.png',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: '/files/03-Greeny/jiwon.jpeg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 7,
        seller_id: 3,
        views: 20,
        title: '좋음',
        content: '드디어 가지가 돋았다. \n 기분 좋아라 랄랄라',
        extra: {
          plantState: '좋음',
          action: '가지',
          actionDate: '2024-08-27',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: '/files/03-Greeny/jiwon.jpeg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      {
        _id: await nextSeq('post'),
        type: 'diary',
        product_id: 7,
        seller_id: 3,
        views: 50,
        title: '영양제 투입 - 빨리 자라길...',
        content: '가지가 돋아나고 있어서 \n 영양이 많이 필요한 것 같아\n 영양제를 꽂아줬다.',
        extra: {
          plantState: '좋음',
          action: '영양',
          actionDate: '2024-08-28',
        },
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: '/files/03-Greeny/jiwon.jpeg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
      },
      //게시글
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '물을 하루에 한 번 주는데 너무 많이 주는 걸까요?',
        content: '난데없이 지인한테 식물을 선물받아서 난생 처음으로 식물을 키워봅니다. \n 죽이기는 싫어서 키워보려는데 모르는 게 많아서 도움을 요청합니다.',
        repliesCount: 2,
        replies: [
          {
            _id: 1,
            user: {
              _id: 2,
              name: '선장',
              image: '/files/03-Greeny/mincheol.jpg',
            },
            content: '물은 하루에 한 번 주는 것이 좋습니다. \n 하지만 식물마다 다르니 식물의 특성에 맞게 주세요.',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
          {
            _id: 2,
            user: {
              _id: 1,
              name: '쑥쑤루쑥',
              image: '/files/03-Greeny/leeBadcuk.jpg',
            },
            content: '아니요. 무슨 꽃인지에 따라 다르고 환경에 따라 다르죠.',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 1000,
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: '/files/03-Greeny/jiwon.jpeg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'qna',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '이거 혹시 병 걸린걸까요?ㅜ',
        content: '며칠 전 부터 이상해지더니\n오늘 보니까 이렇게 됐는데\n병 걸린걸까요?\n어떻게 해야할까요?ㅜㅜ',
        repliesCount: 0,
        replies: [],
        views: 0,
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
        ],
        user: {
          _id: 2,
          name: '선장',
          image: '/files/03-Greeny/mincheol.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'qna',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '서울에서 영양제 제일 싼 곳 없나요?',
        content: '식물이 좀 빨리 자라면 좋을 것 같아서 영양제를 무더기로 사려는데\n 제일 싼 곳 좀 정보 공유받고 싶어요.',
        repliesCount: 1,
        replies: [
          {
            _id: 3,
            user: {
              _id: 1,
              name: '쑥쑤루쑥',
              image: '/files/03-Greeny/leeBadcuk.jpg',
            },
            content: '영양제 가격 다 비슷비슷합니다. 그냥 근처 화원 가서 구매하세요.',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 13,
        image: [
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
        ],
        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'qna',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '식물 키우는 분들끼리 정모나 벙개 있나요?',
        content: '정모나 벙개에 참여하고 싶은데 혹시 그런 모임이 있을까요?',
        repliesCount: 1,
        replies: [
          {
            _id: 4,
            user: {
              _id: 1,
              name: '쑥쑤루쑥',
              image: '/files/03-Greeny/leeBadcuk.jpg',
            },
            content: '영양제 가격 다 비슷비슷합니다. 그냥 근처 화원 가서 구매하세요.',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 7,
        image: [],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: '/files/03-Greeny/jiwon.jpeg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'qna',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '이 꽃의 이름이 뭔가요?',
        content: '어디서 선물받았는데 무슨 꽃인지 잊어버렸어요...',
        repliesCount: 0,
        replies: [],
        views: 23,
        image: [
          {
            path: `/files/${clientId}/PlantImg4.png`,
            name: 'PlantImg4.png',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: '/files/03-Greeny/jiwon.jpeg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'qna',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '식물 분양 받으실 분 계신가요?',
        content: '키우던 식물(커피나무)이 잘 자라서 열매가 많이 맺혔는데, 너무 많은 것 같아서요\n 가져가셔서 겸사겸사 커피도 드시고 키우실 분 계신가요? ',
        repliesCount: 1,
        replies: [
          {
            _id: 5,
            user: {
              _id: 1,
              name: '쑥쑤루쑥',
              image: '/files/03-Greeny/leeBadcuk.jpg',
            },
            content: '저요 저요!!!\n 줄 서봅니다.',
            createdAt: getTime(-2, -60 * 60 * 1),
            updatedAt: getTime(-1, -60 * 60 * 20),
          },
        ],
        views: 23,
        image: [
          {
            path: `/files/${clientId}/PlantImg4.png`,
            name: 'PlantImg4.png',
          },
        ],
        user: {
          _id: 3,
          name: '금전수 장인',
          image: '/files/03-Greeny/jiwon.jpeg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'qna',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '오늘의 관세음보살이!',
        content: '제 관세음보살이 구경하고가세요~! \n벌써 입양한지 20일째입니다요~',
        repliesCount: 0,
        views: 30,
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
        ],
        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'free',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '식린이 2일차...',
        content: '친구의 선물로 급작스럽게 식집사가된 식린이입니다...!! \n아직 부족하지만 그래도 제 식물 자랑하고 싶어 한번 올려봐요!',
        repliesCount: 1,
        replies: [
          {
            _id: 1,
            user: {
              _id: 1,
              name: '쑥쑤루쑥',
              image: '/files/03-Greeny/leeBadcuk.jpg',
            },
            content: '누가 댓글좀 달아주세요ㅜㅜ',
            createdAt: getTime(-2, -60 * 60 * 20),
            updatedAt: getTime(-2, -60 * 60 * 2),
          },
        ],
        views: 0,
        image: [
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
        ],
        user: {
          _id: 4,
          name: '식집사',
          image: '/files/03-Greeny/plant1.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'free',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '안녕하세요!',
        content: '식물을 키우진않지만 키우고싶어하는 식집사입니다! \n입양전에 한번 인사드릴려고 글한번 작성해봐여! \n다들 친하게 친해요!',
        repliesCount: 2,
        replies: [
          {
            _id: 1,
            user: {
              _id: 1,
              name: '쑥쑤루쑥',
              image: '/files/03-Greeny/leeBadcuk.jpg',
            },
            content: '안녕하세요! 친하게 지내요!',
            createdAt: getTime(-2, -60 * 60 * 20),
            updatedAt: getTime(-2, -60 * 60 * 2),
          },
          {
            _id: 2,
            user: {
              _id: 4,
              name: '식집사',
              image: '/files/03-Greeny/plant1.jpg',
            },
            content: '안녕하세요! 자주 만났으면 좋겠어요!',
            createdAt: getTime(-2, -60 * 60 * 20),
            updatedAt: getTime(-2, -60 * 60 * 2),
          },
        ],
        views: 30,
        image: [],
        user: {
          _id: 5,
          name: '식물고수',
          image: '/files/03-Greeny/plant2.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'free',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '집에 가고싶어요..',
        content: '우리 식물 전수씨 보고싶어서 얼른 퇴근하고싶어요,, \n기다려라 전수씨!! 내가 금방 갈게!!',
        replies: [
          {
            _id: 1,
            user: {
              _id: 4,
              name: '식집사2',
              image: '/files/03-Greeny/plant1.jpg',
            },
            content: '이름이 전수씨ㅋㅋㅋ 너무 웃기네요~',
            createdAt: getTime(-2, -60 * 60 * 20),
            updatedAt: getTime(-2, -60 * 60 * 2),
          },
        ],
        views: 0,
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
        ],
        user: {
          _id: 1,
          name: '쑥쑤루쑥',
          image: '/files/03-Greeny/leeBadcuk.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'free',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '베란다 이렇게 꾸며봤어요~',
        content: '이렇게 하니까 너무 이쁘네요.\n자연에 있는 것 같아요 ㅎㅎ',
        repliesCount: 1,
        replies: [
          {
            _id: 1,
            user: {
              _id: 4,
              name: '식집사',
              image: '/files/03-Greeny/plant1.jpg',
            },
            content: '우왕 넘 이뻐요! 저도 이렇게 꾸며보고 싶네요~',
            createdAt: getTime(-2, -60 * 60 * 20),
            updatedAt: getTime(-2, -60 * 60 * 2),
          },
        ],
        views: 0,
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
        ],
        user: {
          _id: 2,
          name: '선장',
          image: '/files/03-Greeny/mincheol.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'planterior',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '현관에 이렇게 하니까 엄청 마음에 들어요 ㅎㅎ',
        content: '현관쪽이 너무 허전해서 항상 꾸미고 싶었는데\n이렇게 꾸미니까 딱 맘에 들어요!',
        repliesCount: 2,
        replies: [
          {
            _id: 1,
            user: {
              _id: 4,
              name: '식집사',
              image: '/files/03-Greeny/plant1.jpg',
            },
            content: '오와 이렇게 현관 꾸미니까 너무 이쁘네요',
            createdAt: getTime(-2, -60 * 60 * 20),
            updatedAt: getTime(-2, -60 * 60 * 2),
          },
          {
            _id: 2,
            user: {
              _id: 4,
              name: '식집사',
              image: '/files/03-Greeny/plant1.jpg',
            },
            content: '어떤 식물인지 알 수 있을까요?',
            createdAt: getTime(-2, -60 * 60 * 20),
            updatedAt: getTime(-2, -60 * 60 * 2),
          },
        ],
        views: 0,
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
          {
            path: `/files/${clientId}/PlantImg1.png`,
            name: 'PlantImg1.png',
          },
          {
            path: `/files/${clientId}/PlantImg2.png`,
            name: 'PlantImg2.png',
          },
        ],
        user: {
          _id: 2,
          name: '선장',
          image: '/files/03-Greeny/mincheol.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'planterior',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '이렇게 꾸며보는 것 어떨까요?',
        content: '거실 한 쪽 면이 허전해서 이렇게 꾸며볼까 하는데\n조언해주실 수 있으실까요?',
        views: 0,
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
        ],
        user: {
          _id: 4,
          name: '식집사',
          image: '/files/03-Greeny/plant1.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'planterior',
        },
      },
      {
        _id: await nextSeq('post'),
        type: 'post',
        title: '화장실 좀 꾸며봤어요',
        content: '인테리어 겸 공기 정화하게 이렇게 뒀습니다!\n이쁘죠~',
        repliesCount: 1,
        replies: [
          {
            _id: 1,
            user: {
              _id: 4,
              name: '식집사',
              image: '/files/03-Greeny/plant1.jpg',
            },
            content: '이렇게 꾸며놓으니까 깔끔하면서도 이쁘네요.\n좋은 플랜테리어 감사합니다!',
            createdAt: getTime(-2, -60 * 60 * 20),
            updatedAt: getTime(-2, -60 * 60 * 2),
          },
        ],
        views: 0,
        image: [
          {
            path: `/files/${clientId}/PlantImg3.png`,
            name: 'PlantImg3.png',
          },
        ],
        user: {
          _id: 5,
          name: '식물고수',
          image: '/files/03-Greeny/plant2.jpg',
        },
        createdAt: getTime(-2, -60 * 60 * 1),
        updatedAt: getTime(-1, -60 * 60 * 20),
        extra: {
          category: 'planterior',
        },
      },
    ],
    // 코드
    code: [
      {
        _id: 'activePost',
        title: '활성 게시판',
        codes: [
          {
            sort: 2,
            code: 'AP01',
            value: '문의 게시판',
            active: false, // 활성 여부
          },
          {
            sort: 1,
            code: 'AP02',
            value: '정보 공유', // 게시판 이름
            active: true,
          },
          {
            sort: 3,
            code: 'AP03',
            value: '음악 신청',
            active: true,
          },
        ],
      },
    ],
    // 설정
    config: [
      {
        _id: 'shippingFees',
        title: '배송비',
        value: 3500,
      },
      {
        _id: 'freeShippingFees',
        title: '배송비 무료 금액',
        value: 50000,
      },
    ],
  };
};
