import localFont from 'next/font/local';
import styles from '@/app/(greeny)/(home)/Home.module.scss';
import type { Metadata } from 'next';
import '@/styles/reset.css';
import '@/styles/common.css';
import '@/styles/variable.css';

const pretendard = localFont({
  src: '../../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <head>
        <meta charSet="UTF-8" />
        <link rel="icon" type="image/x-icon" href="/images/favicon.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Greeny</title>
      </head>
      <body>
        <div className={styles.root}>
          <main className={styles.main}>{children}</main>
        </div>
      </body>
    </html>
  );
}
